version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: rewrite
  reviewers:
  - DeflatedPickle
  assignees:
  - DeflatedPickle
  labels:
  - dependencies
  - dependabot
