version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "monthly"
    target_branch: "master"
    default_reviewers:
      - "DeflatedPickle"
    default_assignees:
      - "DeflatedPickle"
    default_labels:
      - "dependencies"
      - "dependabot"