name: Gradle Dist

on: [ push, workflow_dispatch ]

jobs:
  clear:
    name: Delete old dist-latest release
    runs-on: ubuntu-latest

    steps:
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: "dist-latest"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: clear
    continue-on-error: true

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        task: [ distZip ]
        java-v: [ 8, 11, 16 ]
        java-d: [ adopt-hotspot, adopt-openj9, temurin, zulu ]

    name: Building ${{ matrix.task }} for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-v }}
          distribution: ${{ matrix.java-d }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew --no-daemon ${{ matrix.task }} -Ppre=${GITHUB_SHA::7}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: "./build/distributions/*"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "dist-latest"
          prerelease: true
          files: ./build/distributions/*
