name: Gradle Dist

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    continue-on-error: true

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        task: [ distZip, distTar ]
        java-v: [ 8, 11, 16 ]
        java-d: [ adopt-hotspot, adopt-openj9 ]

    # name: Building Jar for ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-v }}
          distribution: ${{ matrix.java-d }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew --no-daemon ${{ matrix.task }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: "./build/distributions/*"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "dist-latest"
          prerelease: true
          files: ./build/distributions/*
