# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle Dist

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    continue-on-error: true
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        task: [distZip, distTar]
        java-v: [8, 9, 11, 16]
        java-d: [adopt]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-v }}
        distribution: ${{ matrix.java-d }}
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew ${{ matrix.task }}
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Quiver-${{ matrix.java-d }}${{ matrix.java-v }}
        path: ./build/distributions

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./build/distributions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
